### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by jmls** [ngx-fomantic-ui/ngx-fomantic-ui#1]
I have been a long-time user of both semantic-ui and ng-semantic-ui so am very pleased that someone has taken up the reins and restarted the project

However, I cannot seem to get going - I'm following the "getting started" but the `npm install` seems to install an older version (there is no FomanticUIModule) 

do you have a more up to date release ? Or am I doing something wrong ?

**Comment by TryHardDood** [comment]
Hi!
I'll push an update to npm shortly, after that you can use FomanticUIModule

**Comment by jmls** [comment]
ah, perfect. thanks.

**Comment by jmls** [comment]
more than happy to help out with this lib - starting a new project and want to use this, so it's going to get some serious tyre kicking ;)

**Comment by TryHardDood** [comment]
Pushed an update to npm. `ngx-fomantic-ui@0.11.0`
Please reinstall it and then you can use it.
