### ISSUE TITLE
fui-multi-select and formControlName / reactive forms

### ISSUE THREAD

**Issue by jmls** [ngx-fomantic-ui/ngx-fomantic-ui#11]
I'm having a problem with the above combination. if I have this html

```
                <fui-multi-select class="selection"
                          formControlName="policies"
                          [options]="availablePolicies"
                          labelField="name"
                          [isSearchable]="searchable"
                          [isDisabled]="disabled"
                          [hasLabels]="!hideLabels"
                          [showCountText]="'Select'"
                          #policySelection>
                    <fui-select-option *ngFor="let option of policySelection.filteredOptions"
                               [value]="option"></fui-select-option>
                </fui-multi-select>
```

then the select is not instantiated with the current value of the `polcies` formControl

if, however, I have this html instead

```
            <div class="field">
                <input type="text" formControlName="policies">
            </div>
```

I get `[object Object],[object Object],[object Object]` displayed in the text box, which shows that the form data is present, just not showing the the fui-multi-select control

**Comment by TryHardDood** [comment]
Could you please create a [stackblitz.com](https://stackblitz.com/edit/angular-dnteqt) with your problem?

**Comment by jmls** [comment]
I've created a demo where it works, but only for single-value arrays `['a','b','c']` etc. I just cannot get the multi-select to initially populate if I pass in an array of objects instead

https://stackblitz.com/edit/angular-cksgrt

I know that I;m missing something very basic here ..

**Comment by TryHardDood** [comment]
If you're using it like in the stackblitz example then everything should work as expected.
It has arrays of objects and it still gets initially populated.

I can't really understand your problem, could you explain it better?
Also please edit the stackblitz so I can see what's not working for you.

**Comment by oludare1001** [comment]
Hello, i have two fui-select on the same form; but the options are conflicting.
The options on the first fui-select is also showing on the second.

**My Interface**
export interface IOption {
    id?: number;
    name: string;
}


**My Arrays**

states: IOption[] = [
    {id: 1, name: "Florida"},
    {id: 2, name: "Alaska"}
  ]
 
  countries: IOption[] =  [
    {id: 1, name: "United States"},
    {id: 2, name: "Canada"},
    {id: 3, name: "UK"}
  ];


**fui-select**
1. 
<fui-select class="selection"
                                        [(ngModel)]="selectedState"
                                        placeholder="Select State"
                                        [options]="states"
                                        labelField="name"
                                        [isSearchable]="searchable"
                                        [isDisabled]="disabled"
                                        formControlName="state"
                                        #select>
                              <fui-select-option *ngFor="let state of select.filteredOptions"
                                       [value]="state">
                              </fui-select-option>
                            </fui-select>


2.  <fui-select class="selection"
                                       [(ngModel)]="selectedCountry"
                                       placeholder="Select Country"
                                       [options]="countries"
                                        labelField="name"
                                        formControlName="country"
                                        [isSearchable]="searchable"
                                        [isDisabled]="disabled"
                                        #select>
                                       <fui-select-option *ngFor="let country of select.filteredOptions"
                                                 [value]="country">
                              </fui-select-option>
                            </fui-select>


I don't understand why this is happening. 
Please I need assistance @TryHardDood 
Thanks

**Comment by TryHardDood** [comment]
Hi @oludare1001,
The problem is the selector you're requesting `.filteredOptions` from. 
You'll need to name them differently because it'll use the values from the first element that matches the `#select` selector.

See here: [Stackblitz](https://stackblitz.com/edit/ngx-fomantic-ui-issues-11?file=src%2Fapp%2Fapp.component.html)

**Comment by oludare1001** [comment]
This solved my problem!!
I am so grateful @TryHardDood 

God bless you

**Comment by oludare1001** [comment]
Hi @TryHardDood 

I am trying to populate a fui-select with dynamic options from a dynamic array.
I have not been able to get this done.

Please your assistance will be greatly appreciated.

**Comment by TryHardDood** [comment]
Hi @oludare1001!
Please provide some code preferably on Stackblitz.com so I can help you.

Thanks

oludare1001 <notifications@github.com> ezt írta (időpont: 2020. okt. 6., K
18:22):
