### ISSUE TITLE
Current progress of the reboot

### ISSUE THREAD

**Issue by TryHardDood** [ngx-fomantic-ui/ngx-fomantic-ui#30]
**First of all, why do we need a reboot?**

Currently the current code is working fine, however because it was written about 2 or more years ago it aged well and the maintainability is getting worse because of the continuous Angular/Typescript updates.

**Allright, then when will it be finished?**

Well, I making it in my free time so there's that.
I can't really give an ETA for the reboot. Hopefully soon enough.

**Okay, what's going to happen to the current version?**

I will keep providing updates and bugfixes if I can but the main priority will be the reboot.

*If you're willing to contribute feel free to do a Pull Request. Help is greatly appreciated.*

---

- [x] Accordion
- [ ] Calendar
- [x] Checkbox
- [x] Collapse
- [ ] Dimmer
- [ ] Dropdown
- [ ] Modal
- [ ] Popup
- [ ] Progress
- [ ] Rating
- [ ] Search
- [ ] Sidebar
- [ ] Slider
- [ ] Tabs
- [ ] Toast
- [ ] Transition

**Comment by darckoune** [comment]
Hello ! I'm following your work on this repository and I've migrated my app from ng2-selantic-ui to ngx-fomantic-ui in the previous days without problems :)

I'm really happy that you started working on a reboot ! I've no experience in making angular component libraries but I'll try to help if I can (I will wait that a few of the modules are done to have examples to help me)

Also, it would be really great if this reboot was compatible with Angular Ivy. For now it isn't (or at least I haven't make it work) and it prevents me from switching to Ivy in my project.

**Comment by TryHardDood** [comment]
Hello!
First of all thank you for using it :)

I working hard on the reboot however my free time is limited and I have other things to do, so any help is greatly appreciated. 

Currently Angular Ivy is not my main priority but I'll keep this in mind when writing the modules.
Once I created the modules 70% I'll push it to a public repository so people like you can see it and may try to help with the other modules.
