### ISSUE TITLE
Documentation website is not runnable

### ISSUE THREAD

**Issue by Hermel** [ngx-fomantic-ui/ngx-fomantic-ui#33]
When trying to start / bulid the ngx-fomantic-ui website locally,
several problems occur:
1. When running `npm start` - the following problem occures:

> NullInjectorError: StaticInjectorError(AppModule)[FuiSidebarSibling -> Renderer2]: 
  StaticInjectorError(Platform: core)[FuiSidebarSibling -> Renderer2]: 
    NullInjectorError: No provider for Renderer2!

2. when trying to run the script `build:docs:prod` - the following problem occures:
> ERROR in ..\..\ngx-fomantic-ui\ngx-fomantic-ui.ts(7,2): Error during template compile of 'FuiSidebarModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

probably a problem in appModule.

**Comment by TryHardDood** [comment]
Hi!
Try it with `npm run serve:docs` or `npm run build:docs:prod`

**Comment by Hermel** [comment]
Thanks for the quick reply @TryHardDood !🥇 

I've tried it but the errors still happen.

**Comment by TryHardDood** [comment]
Are you running the command from the root of the project?

**Comment by Hermel** [comment]
Yes. (tried also from the internal docs folder without success).
Maybe I'm missing something in the way?

The steps I preformed:
1. clone the project
2. npm install
3. npm run build:docs:prod or npm run serve:docs

**Comment by TryHardDood** [comment]
Currently I'm not at my office and I cannot test it.
However, the error's cause is may be the Angular 8 upgrade.

https://github.com/ngx-fomantic-ui/ngx-fomantic-ui/blob/30c358633449392d399405a0a16ba903588f3743/projects/ngx-fomantic-ui/src/modules/sidebar/components/sidebar-container.ts#L24

Please try to change static value to true and run the `npm run build:lib:prod` and the `npm run serve:docs` commands.

It's weird because if this is not working for you it shouldn't work for the live documentation site. Every pull-request is checked by Travis-CI and Netlify. This shouldn't be happening. Only tomorrow I can look into this more if the above mentioned change doesn't work for you.

**Comment by Hermel** [comment]
I've tried it now,
the building fails for :
> ERROR in ..\..\ngx-fomantic-ui\ngx-fomantic-ui.ts(7,2): Error during template compile of 'FuiSidebarModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

**Comment by TryHardDood** [comment]
After a little research I found out that this is an angular compiler bug.

https://github.com/angular/angular-cli/issues/10832

**Comment by Hermel** [comment]
Iv'e looked more into it,
by adding the angular path to paths in tsconfig like:
`      "@angular/*": ["../node_modules/@angular/*"]
`
 I was able to serve the website .
Only problem now is in the modal.page.ts and test.page.ts (for the toast component) in the static View child.
I will be happy if you could look more into it when you will be in the office, I think it's occuring because of the migration to Angular 8 as you mentioned before.
the error is: 
>    ERROR in projects/ngx-fomantic-ui-docs/src/app/pages/development/test/test.page.ts(11,33): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
      Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.

local resolve for it is changing the 'static' to 'read'. It won't make the modal / toast pages work - but the rest of the site will be ok :)

**Comment by TryHardDood** [comment]
After cloning the project I did the following:

- `npm install`
- `npm run build:lib:prod`
- `npm run serve:docs`

And everything is working fine for me.

Can you tell me which version of Angular are you using?

I'm using with this version:
```
Angular CLI: 8.1.2
Node: 10.15.3
OS: win32 x64
Angular: 8.2.0-next.2
```

**Comment by Hermel** [comment]
Well,
I tried it again now on a different computer (Angular 8, win32 x64, node v10.16.0) and **it** **works**.
Maybe I had an env problem on the other computer. 
I thought about maybe adding a docker wrapping for the documentation project for providing an option to run the documentation website over a docker server / kubernetes, etc.

Thanks for the help anyway :)
