### ISSUE TITLE
Fomantic UI

### ISSUE THREAD

**Issue by brunotourinho** [ngx-fomantic-ui/ngx-fomantic-ui#53]
Hey @TryHardDood,

I'm a FUI user and started learning Angular 8.

In the FUI GitHub there's a few people also interested in a port.

I know it's hard to keep up with the development alone. 

Maybe you can find someone there who can help you. [FUI/issues/989](https://github.com/fomantic/Fomantic-UI/issues/989#issuecomment-527149382) 

Best regards!

Bruno

**Comment by TryHardDood** [comment]
Hello @brunotourinho,

Lately I didn't have much time for this and yea, it would be great to have more people to work on it.
Thanks, I'll check it out.
