### ISSUE TITLE
fui-tabset cannot work in Angular 9

### ISSUE THREAD

**Issue by alfred-f-yu** [ngx-fomantic-ui/ngx-fomantic-ui#61]
Code:
`<fui-tabset style="padding-left: 0;padding-right: 0">`
  `<div class="ui top attached tabular menu">`
    `<a class="item" fuiTabHeader="1">111</a>`
    `<a class="item" fuiTabHeader="2">222</a>`
    `<a class="item" fuiTabHeader="3">333</a>`
  `</div>`
 ` <div class="ui bottom attached segment" style="border: none;" fuiTabContent="1">`
    `.......`
  `</div>`
  `<div class="ui bottom attached segment" style="border: none;" fuiTabContent="2">`
   ` .......`
  `</div>`
  `<div class="ui bottom attached segment" style="border: none;" fuiTabContent="3">`
   ` .......`
  `</div>`
`</fui-tabset>`

ERROR TypeError: Cannot set property 'isActive' of undefined
    at FuiTabset.set activeTab [as activeTab] (vendor.js:346545)
    at FuiTabset.activateFirstTab (vendor.js:346568)
    at FuiTabset.loadTabs (vendor.js:346706)
    at FuiTabset.ngAfterContentInit (vendor.js:346561)
    at callHook (vendor.js:41649)
    at callHooks (vendor.js:41613)
    at executeInitAndCheckHooks (vendor.js:41554)
    at refreshView (vendor.js:47941)
    at refreshComponent (vendor.js:49332)
    at refreshChildComponents (vendor.js:47630)

fuiTabHeader and  fuiTabContent exist in the codes. I known if I missed fuiTabHeader or fuiTabContent, the same errors will happend.  The error only happened in Angular 9, the same codes can work properly in Angular 8 or older.

**Comment by alfred-f-yu** [comment]
This bug can be fixed.
[https://github.com/edcarroll/ng2-semantic-ui/issues/447#issuecomment-611118980](url)

**Comment by WuglyakBolgoink** [comment]
@alfred-f-yu I have the same error in Angular 10

**Comment by WuglyakBolgoink** [comment]
> This bug can be fixed.
> [https://github.com/edcarroll/ng2-semantic-ui/issues/447#issuecomment-611118980](url)

fixed link
https://github.com/edcarroll/ng2-semantic-ui/issues/447#issuecomment-611118980
