### ISSUE TITLE
odd issue with tabs

### ISSUE THREAD

**Issue by jmls** [ngx-fomantic-ui/ngx-fomantic-ui#8]
When initializing a tabset with data from an async source, 

#1 the tabs don't get drawn until you click on the tab
#2 you have to click twice on a tab to select it

If I add `changeDetection: ChangeDetectionStrategy.OnPush` to the component and 
```
 setTimeout(() => {
            this.changeDetectorRef.markForCheck();
        });
```

to `ngOnInit()` then the tabs do get drawn, but I still need to click twice on a tab

the html code is
```
<div class="ui top attached tabular menu">
        <a class="item" *ngFor="let item of items; let index = index;" fuiTabHeader="{{index}}">{{item.name}}</a>
      </div>
```

![image](https://user-images.githubusercontent.com/929523/59702097-e2832400-91ee-11e9-8cd6-b5260f8a4375.png)

**Comment by jmls** [comment]
maybe related https://github.com/edcarroll/ng2-semantic-ui/issues/274

**Comment by TryHardDood** [comment]
Can you create a [stackblitz](https://stackblitz.com) with the bug?

I can't really reproduce it.
