### ISSUE TITLE
Remove console.log's

### ISSUE THREAD

**Issue by WuglyakBolgoink** [ngx-fomantic-ui/ngx-fomantic-ui#80]
https://github.com/ngx-fomantic-ui/ngx-fomantic-ui/blob/41edcb2ac98df9bd5a142b195c2cacd6abb83e47/projects/ngx-fomantic-ui-docs/src/app/pages/modules/transition/transition.page.ts#L58

https://github.com/ngx-fomantic-ui/ngx-fomantic-ui/blob/41edcb2ac98df9bd5a142b195c2cacd6abb83e47/projects/ngx-fomantic-ui-docs/src/app/pages/modules/transition/transition.page.ts#L136

**Comment by TryHardDood** [comment]
It's just for the example.
Callbacks are not required some can be left out.
