### ISSUE TITLE
missed CHANGELOG

### ISSUE THREAD

**Issue by WuglyakBolgoink** [ngx-fomantic-ui/ngx-fomantic-ui#83]
any info for this? Where I can see what was changed in last releases?

Because after upgrade to last version I have now some errors with modals:

```
Generic type 'FuiModal<T, U>' requires 2 type argument(s).

43         private modal: FuiModal<void, IFiltersModalForm, IFiltersModalForm>
```

**Comment by TryHardDood** [comment]
Hi!
Sorry for not warning about the breaking change. This is the only breaking change in the Angular 10 version everything else should work just fine as before.

Here's the details: 
https://github.com/ngx-fomantic-ui/ngx-fomantic-ui/commit/a540c415ff22aa2c2c326e56b4415ddf11cb241b#diff-7f7b32eab09af4506c0d0f2426f50287

Basically you'll need to replace `FuiModal` with `FuiBaseModal`
Next time I'll provide a changelog for the update.

**Comment by WuglyakBolgoink** [comment]
@TryHardDood yup. I already reviewed all last changes and found this renaming :-)

Thank you!
