### ISSUE TITLE
Populating <fui-multi-select> dropdown item from a dynamic array

### ISSUE THREAD

**Issue by NickOludare** [ngx-fomantic-ui/ngx-fomantic-ui#85]
@TryHardDood 
See here: [Stackblitz](https://stackblitz.com/edit/angular-ivy-tgthdh?file=src%2Fapp%2Fapp.component.html)

Thanks

**Comment by TryHardDood** [comment]
@NickOludare 

Check this out: https://stackblitz.com/edit/angular-ivy-lo4qpf

**Comment by NickOludare** [comment]
This solved my problem @TryHardDood 
I am so grateful. God bless you

If I have multiple fui-multi-select and I want to populate each of them just the way you just did, please how do I select each of the fui-multi-select?

**Comment by TryHardDood** [comment]
You can select them in a QueryList with ContentChild**ren**

https://angular.io/api/core/ContentChildren

**Comment by NickOludare** [comment]
Done @TryHardDood 

Everything is working perfectly now.
I am so grateful.

God bless you
