### ISSUE TITLE
FUI Toast update demo example (+ Angular 10 Support)

### ISSUE THREAD

**Issue by evgenius1424** [ngx-fomantic-ui/ngx-fomantic-ui#86]
Hi, I've tried to use fui toast but I couldn't (I use latest 0.11.7)

Problems:

1) I was not able to find documentation for toast usage at the demo page.
BTW I've expected that click on toast segment will produce real toast. (like here https://fomantic-ui.com/modules/toast.html)

https://ngx-fomantic-ui.netlify.app/#/modules/toast - but it just removes html

2) I was able to find in code fui-container component, but when I add something to it just print toast title, message without fomantic styles (Angular 9)

3) I seems that Angular 10  is not supported actually.

    ERROR in node_modules/ngx-fomantic-ui/fui.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

p.s. I can help with contribution if you answer at this comment|)

**Comment by TryHardDood** [comment]
Hi!
I haven't tested it with the latest Angular version, something must've broke with an update. I'll look into it when I have some free time. Your contribution would be a big help.
However you can find some examples of fui-toast [here](https://github.com/ngx-fomantic-ui/ngx-fomantic-ui/blob/master/projects/ngx-fomantic-ui-docs/src/app/pages/development/test/test.page.ts)

**Comment by evgenius1424** [comment]
I've found a solution. I'm not sure why but there is some logic at constructor of fui-toast. 

https://ngx-fomantic-ui.netlify.app/#/development/test - if you click to **Add toast** button you will see that **ui toast** class is not added. Move to onInit helps.

I plan to test any maybe fix some new toast related issues and will raise PR. Thanks.

**Comment by evgenius1424** [comment]
Hi @TryHardDood I've raised simple PR to fix toast issue.

https://github.com/ngx-fomantic-ui/ngx-fomantic-ui/pull/87

Please link PR to this issue and release the component.

**Comment by evgenius1424** [comment]
Hi. Can you please close this issue and release 0.11.8?
